Js implemented in mobile menu
HossainAraf/Portfolio-Mobile-First pull request #10
Opened 2023-06-26 14:26 UTC by HossainAraf

We have implemented the following features  in mobile menu:

- When the user clicks (or taps) the hamburger button, the mobile menu appears. [Code](https://github.com/HossainAraf/Portfolio-Mobile-First/blob/c75452596bd3ab6896d67158917ab12d0add2df9/app.js#L8C1-L25C2)
- When the user clicks (or taps) the close (X) button, the mobile menu disappears. [Code-1](https://github.com/HossainAraf/Portfolio-Mobile-First/blob/c75452596bd3ab6896d67158917ab12d0add2df9/app.js#L10C1-L10C1) [Code-2](https://github.com/HossainAraf/Portfolio-Mobile-First/blob/c75452596bd3ab6896d67158917ab12d0add2df9/app.js#L27)
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears. [Code](https://github.com/HossainAraf/Portfolio-Mobile-First/blob/c75452596bd3ab6896d67158917ab12d0add2df9/app.js#L36C1-L41C1)
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed. [Code](https://github.com/HossainAraf/Portfolio-Mobile-First/blob/c75452596bd3ab6896d67158917ab12d0add2df9/index.html#L21-L22)

2023-06-26 18:19 UTC, Strangeal reviewed
Hi @HossainAraf, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] It appears that the project was intended to be completed using pair programming. However, based on the commit history, it seems that you completed the project alone instead of collaborating with your coding partner. For the purpose of maintaining the integrity of the pair programming process, I kindly request you to reach out to your coding partner and work together on the project before resubmitting it for review.  

  - [ ] In case you encountered any difficulties or issues with your coding partner that prevented you from collaborating, I encourage you to contact Student Success ([Success@microverse.org](mailto:Success@microverse.org)) to address the situation and seek assistance. It's important to adhere to the principles of pair programming and communicate any challenges you may face in order to ensure a fair and effective learning environment.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-26 19:16 UTC, HossainAraf commented
Dear @Strangeal, 
Perhaps you missed that one of my coding partners participated. Please, find the commit [link](https://github.com/HossainAraf/Portfolio-Mobile-First/pull/10/commits/615d51635103457d9fea467255d92e9149c87365) 
So, Please proceed with reviewing the file. Thanks.

2023-06-27 13:51 UTC, NahnahAJ commented
## Project Status: INVALIDATED :red_circle: 
Hi @HossainAraf , 

While you made a great effort in this project, I can't go ahead and review your code.
<img src="https://media2.giphy.com/media/TiUYdWptTqn8yOk1Dp/giphy.gif"/>

## Invalid Code Review Request

This is because you have submitted a project, that is missing the `.eslintrc.json file` which is in charge of the `Eslint` checks or JAVASCRIPT LINTER CHECKS so kindly ensure that you have properly installed the [HTML, CSS, AND JAVASCRIPT LINTERS](https://github.com/microverseinc/linters-config/tree/master/html-css-js) in your project :100: 
- Your Current checks 
![image](https://user-images.githubusercontent.com/102699958/233022204-f6fdeb52-df69-4bdf-bcc9-aaa0984bb6a2.png)

- What you should have
![image](https://user-images.githubusercontent.com/102699958/233023284-08bc261d-5b90-43d1-aa37-2f706f2a030c.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-28 04:19 UTC, divinecharlotte requested changes
Hi @Team , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- Descriptive pr 👍 
- Descriptive readme 👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 04:19 UTC, divinecharlotte commented on index.html
> +        <li class="menu-item"><a href="#work" title="Go to services">Services</a></li>
- [ ] kindly consider sticking to the design as much as possible by adding the right `text` as the one given in the design to stay consistence with the requirement below 👇 
> You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
<img width="378" alt="Screen Shot 2023-06-28 at 06 16 58" src="https://github.com/HossainAraf/Portfolio-Mobile-First/assets/60146030/a4e8903a-9cfa-4f41-94e8-81f79295a4e2">

2023-06-28 07:47 UTC, levy002 requested changes
## Hello @HossainAraf   , :wave:
### I'm @levy002, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)


## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 07:47 UTC, levy002 commented on index.html
> +        <li class="menu-item"><a href="#form" title="Go to contact">Contact</a></li>
- [ ] Kindly make sure the `About` link directs the user to `about-myself` and `Portfolio` directs to the `work` part of the page.

  ```suggestion
        <li class="menu-item"><a href="#work" title="Go to title">Portfolio</a></li>
        <li class="menu-item"><a href="#about-myself" title="Go to services">About</a></li>
        <li class="menu-item"><a href="#form" title="Go to contact">Contact</a></li>
```

2023-06-28 08:13 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @HossainAraf 

Your project is complete! Great job🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Figma design well followed
- works as expected

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-28 08:26 UTC, merged