Contact Form included for Mobile version
HossainAraf/Portfolio-Mobile-First pull request #3
Opened 2023-06-13 16:03 UTC by HossainAraf

Contact form was added as per the Figma design provided. Following features are added for form validation:

-Name field accepts up to 30 chars.
-Email field accepts only emails;
-Message field accepts up to 500 chars;
-All fields have placeholder text;
-All fields have the correct type;
-A user cannot submit the form if one or more of the fields is empty.

2023-06-13 17:19 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @HossainAraf and @donice👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You lay out the elements on the page using Flexbox. 👍🏽
✅ Name field accepts up to 30 chars✔️
✅ Message field accepts up to 500 chars✔️


## Required Changes ♻️

> - [ ] Since this is a pair programming activity, kindly add the details of your partner (Second Author) in your README file👍
> 
> ![cd2readme](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/b350c13d-9f34-4d27-8bdc-23970b77daf5)
> 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 17:19 UTC, Johnadibe commented on index.html
> +            I’d love to help with it!</p></label>
> - [ ] Good job so far👍, As developers, it is crucial to maintain consistency by adhering to the design templates in Figma. Please pay attention to details such as font choices and spacing (margin) and ensure that they closely match the design provided. By doing so, you can ensure that the visual elements of your application align with the intended design, creating a more cohesive and polished user experience. ☺
> 
> Figma design:
> 
> ![cd-1](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/006a6cff-5c96-46d5-ae63-f599b28b08c3)
> 
> Your design:
> 
> ![cd](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/2c38443d-7cdf-488d-ab59-29f96ebb5a64)
>

2023-06-13 17:19 UTC, Johnadibe commented on style.css
> +}
> - [ ] I recommend incorporating a padding-left property to the form input in order to closely align it with the Figma design. This adjustment will help ensure that the form input closely resembles the desired layout as indicated in the design.👍
> 
> Figma design:
> 
> ![cd1-1](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/0dc17af0-a503-4c33-8b9a-20cacab0d180)
> 
> Your design:
> 
> ![cd1](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/a6f2cf9f-836c-4b2a-a6ff-b5e9e50de334)
>

2023-06-13 17:19 UTC, Johnadibe commented on index.html
> +      <form class="flex-column">
> - [ ] According to the project requirements, it is necessary for the form to gather data by utilizing the `action` and `method` attributes to integrate with the [Formspree service](https://formspree.io/html). I've observed that this particular requirement has not been implemented yet. Therefore, I kindly request you incorporate the mentioned attributes into the form code. By doing so, the form will be able to successfully integrate with the Formspree service. 👍

2023-06-13 17:19 UTC, Johnadibe commented on index.html
> +          <textarea class="form-input" id="message" name="message" type="text" rows="4" placeholder="Write your message here..." maxlength="500"></textarea>
> - [ ] It appears that you haven't included the `required` attribute in the `<textarea>` element. Based on the project requirements, _A user cannot submit the form if one or more of the fields is empty._ Please kindly add the required attribute to the `<textarea>` element to ensure compliance with this requirement. By doing so, users will be prompted to fill in the `<textarea>` before they can successfully submit the form.

2023-06-13 17:19 UTC, Johnadibe commented on index.html
> +        <button class="form-button" type="submit"><p>Get in touch</p></button>
> - [ ] Kindly ensure you implement the hover and pressed button state interactions to match the Figma design as much as possible.👍
> 
> Figma design:
> 
> ![bt](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/40009354/b17263d7-357a-4948-a060-d706891bcbd4)
>

2023-06-14 10:14 UTC, HossainAraf commented on index.html
> +            I’d love to help with it!</p></label>
Thank you. But, I used the css from figma design. The output for these code is not same as the design. So, what should I do now?

2023-06-14 12:36 UTC, HossainAraf commented
I used the css from figma design. The output for these code is not same as the design. Same font family results different from the figma font.

2023-06-14 13:04 UTC, wayungi requested changes
Hi @HossainAraf , 

![image](https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ] All linter checks passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 13:04 UTC, wayungi commented on index.html
> +    </section>
- [ ] Please note that the border-radius in the Figma is smoothly curved and the text **Contact me** is on oneline. Kindly implement this so that your project looks like the design.
![curve](https://github.com/HossainAraf/Portfolio-Mobile-First/assets/99656687/ad76b836-c59f-4263-93be-7c8d4ecb9392)

2023-06-14 13:04 UTC, wayungi commented on index.html
> +      <form class="flex-column" action="#" method="post">
- [ ] Your form should post data using [form spree](https://formspree.io/html/). Please follow the link provided and make sure your form posts to from spree. This is also a project requirement

2023-06-14 14:35 UTC, HossainAraf commented
Hello!
Are you suggesting to change all content of the form or just the action
attribute .

On Wed, 14 Jun 2023 at 14:05, Francis Wayungi ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @HossainAraf <https://github.com/HossainAraf> ,
>
> [image: image]
> <https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png>
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't been addressed yet.
> Highlights
>
>    - All linter checks passing ✔️
>    - Correct GitHub flow ✔️
>    - Descriptive PR body
>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/HossainAraf/Portfolio-Mobile-First/pull/3#discussion_r1229579897>
> :
>
> > +    <section id="form" class="flex">
> +      <form class="flex-column" action="#" method="post">
> +        <div class="form-group">
> +          <label class="form-label" for="name"> <h2>Contact me</h2> <p>If you have an application you are interested in developing, a feature that you need built or a project that needs coding.
> +            I’d love to help with it!</p></label>
> +          <input class="form-input" type="text" id="name" name="name" placeholder="Lorem Ipsum" pattern="[A-Za-z\s\.]+" maxlength="30" required>
> +        </div>
> +        <div class="form-group">
> +          <label class="form-label" for="email"></label>
> +          <input class="form-input" type="email" id="email" name="email" ***@***.***"  ***@***.***+\.[a-z]{2,}$" required>
> +        </div>
> +        <div class="form-group">
> +          <label class="form-label" for="message"></label>
> +          <textarea class="form-input" id="message" name="message" type="text" rows="4" placeholder="Write your message here..." maxlength="500" required></textarea>
> +        </div>
> +        <div class="form-group">
> +        <button class="form-button" type="submit"><p>Get in touch</p></button>
> +        </div>
> +      </form>
> +    </section>
>
>
>    - Please note that the border-radius in the Figma is smoothly curved
>    and the text *Contact me* is on oneline. Kindly implement this so that
>    your project looks like the design.
>    [image: curve]
>    <https://user-images.githubusercontent.com/99656687/245798878-ad76b836-c59f-4263-93be-7c8d4ecb9392.png>
>
> ------------------------------
>
> In index.html
> <https://github.com/HossainAraf/Portfolio-Mobile-First/pull/3#discussion_r1229584869>
> :
>
> > @@ -197,6 +196,27 @@ <h2>About Myself</h2>
>          </ul>
>        </div>
>      </section>
> +    <!-- Form -->
> +    <section id="form" class="flex">
> +      <form class="flex-column" action="#" method="post">
>
>
>    - Your form should post data using form spree
>    <https://formspree.io/html/>. Please follow the link provided and make
>    sure your form posts to from spree. This is also a project requirement
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HossainAraf/Portfolio-Mobile-First/pull/3#pullrequestreview-1479379839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A7A6ILYNJGP4M2W6QTTV26TXLGZIDANCNFSM6AAAAAAZFDR3AQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-06-14 15:27 UTC, abdallahmalima requested changes
Hi @HossainAraf , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![A little bit more](https://user-images.githubusercontent.com/20554583/208236462-13ccd332-b921-416b-a8a9-b831ebd7c79b.gif)


 ## Highlights
   - Use form element✔️
  - Form action and method✔️
  - Form validation✔️
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 15:27 UTC, abdallahmalima commented on index.html
> +      <form class="flex-column" action="https://formspree.io/f/{form_id}" method="post">
- 🙏Please replace `{form_id}` with the actual ID from Formspree. If you log in to Formspree's service at [Formspree website](https://formspree.io/html), you will obtain the real ID. By doing so, your action will be submitted to the correct URL. Your code should resemble the following:
```suggestion
      <form class="flex-column" action="https://formspree.io/f/xoqzgjck" method="post">
```

2023-06-14 15:48 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Correct workflow :heavy_check_mark: 
- Formspree service integrated successfully :heavy_check_mark: 
- Changes implemented :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 16:00 UTC, merged